### ISSUE TITLE
Review 2: Hearing.jsx and CreateTestimony.jsx

### ISSUE THREAD

**Issue by zakgilbert** [alahele/alahele#98]
## Review Branch

review-xxx

## Files to review
* [Hearing.jsx](https://github.com/alahele/alahele/blob/main/app/imports/ui/pages/Hearing.jsx)
* [CreateTestimony.jsx](https://github.com/alahele/alahele/blob/main/app/imports/ui/pages/CreateTestimony.jsx)

## Checklists
* [Architecture](https://github.com/cammoore/campus-cravings/tree/master/checklists/architecture-checklist.md)
* [Design](https://github.com/cammoore/campus-cravings/tree/master/checklists/design-checklist.md)
* [JS](https://github.com/cammoore/campus-cravings/tree/master/checklists/js-checklist.md)
* [React](https://github.com/cammoore/campus-cravings/tree/master/checklists/react-checklist.md)
* [Testing](https://github.com/cammoore/campus-cravings/tree/master/checklists/testing-checklist.md)

## Due date

9/20/2022

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by lisemnilsen** [comment]
CreateTestimony.jsx
- L65, L71 & L77: Remove superfluous code like className="" (the "" is empty).
- Use 'const' and 'let' to simplify the code.

Hearing.jsx:
- Ensure code is readable: The code is deeply nested, so a possibility is to simplify the code by removing unnecessary components and cards. One can see an example of the deeply nested code by looking at L245 - L267. 
- L154 & L266: Is it necessary to have a container inside a container? The layout looks the same if you remove the container from line 154 and 266.
- Simplify the code by importing a component from another file. This will make the code more self-explanatory.

**Comment by tineriver** [comment]
Hearing.jsx
Break up features into components 

CreateTestimony.jsx
Looks good to me.

**Comment by cathy-kim95** [comment]
CreateTestimony.jsx:
L67, L102, L115 Typo

Hearing.jsx:
Design02&07 - there are multiple, deeply nested containers.

**Comment by William-Liang808** [comment]
##CreateTestimony.jsx

- L65, L71, L77: Empty class names
- L2: Useless import for style since it should already be global and usable without importing.

##Hearing.jsx

- L2: Useless import for style since it should already be global and usable without importing.

**Comment by sle417** [comment]
Hearing.jsx
- Code Spacing could be improved to separate containers/sections of component code.
- Comments for certain elements implemented could also help with readability (since its a very long file)
- const mockHearingData could probably be separated outside const Hearing()

CreateTestimony.jsx
- Java doc comments for functions created (date) could help explain what it does & readability

**Comment by eric-song1773** [comment]
Hearing.jsx

- The mockup data can be moved outside of const Hearing for better readability
- In the future, reimplementing the page so that instead of having everything in one page, having multiple component can solve the issue of readability and editing them.

CreateTestimony.jsx
- A lot of the "className = ..." for styling purpose can all be moved into CSS file for better readability and shorter codes.

**Comment by zakgilbert** [comment]
## Hearing.Jsx
    * For the overall page, needs to be splt into three components at the minimu
m.
    * TEST-ACCEPTANCE-01: Each Page has an isDisplayed() acceptance test.

## CreateTestimony.jsx
    * Line 21 - Need comment describing component.
    * TEST-ACCEPTANCE-01: Each Page has an isDisplayed() acceptance test.
